# Generated by Django 5.2.3 on 2025-06-22 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="La fecha a la que aplica esta tasa de cambio.",
                        verbose_name="Fecha de la Tasa",
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                            ("BS", "Bolívar Venezolano"),
                        ],
                        default="USD",
                        help_text="La moneda de la cual se está convirtiendo (ej. USD).",
                        max_length=10,
                        verbose_name="Moneda Origen",
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                            ("BS", "Bolívar Venezolano"),
                        ],
                        default="BS",
                        help_text="La moneda a la cual se está convirtiendo (ej. BS).",
                        max_length=10,
                        verbose_name="Moneda Destino",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor: 1 USD = X BS.",
                        max_digits=10,
                        verbose_name="Tasa de Cambio",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Dólar Estadounidense"),
                            ("EUR", "Euro"),
                            ("BS", "Bolívar Venezolano"),
                        ],
                        default="USD",
                        help_text="Moneda",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización del Registro"
                    ),
                ),
            ],
        ),
    ]
