# Generated by Django 5.2.3 on 2025-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.IntegerField(
                default=0,
                help_text="Nivel de stock en el que el producto se considera 'bajo'.",
                verbose_name="Umbral de Stock Bajo",
            ),
        ),
    ]
