# Generated by Django 5.2.3 on 2025-06-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_low_stock_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price_usd",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Precio de Compra (USD)",
            ),
        ),
    ]
