# Generated by Django 5.2.3 on 2025-06-21 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_product_purchase_price_usd"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Venta"
                    ),
                ),
                (
                    "total_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total USD"
                    ),
                ),
                (
                    "total_bs",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total BS"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cantidad"
                    ),
                ),
                (
                    "unit_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario USD",
                    ),
                ),
                (
                    "subtotal_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal USD"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Venta",
                "verbose_name_plural": "Ítems de Venta",
            },
        ),
    ]
