# Generated by Django 5.2.3 on 2025-06-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="unit_price_bs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Precio Unitario BS",
            ),
            preserve_default=False,
        ),
    ]
